export enum ActionsType {
  CHANGE_CONSTRUCTOR_TYPE = 'CHANGE_CONSTRUCTOR_TYPE',
  SET_CONSTRUCTOR_PARAMS = 'SET_CONSTRUCTOR_PARAMS',
  ADD_TABLE = 'ADD_TABLE',
  UPDATE_TABLE = 'UPDATE_TABLE',
  DELETE_TABLE = 'DELETE_TABLE',
  SELECT_TABLE = 'SELECT_TABLE'
}

export enum ConstructorType {
  new = 'new',
  edit = 'edit'
}
